language: generic

env:
  matrix:
    - EMACS=emacs24
    - EMACS=emacs-snapshot

matrix:
  allow_failures:
    - env: EMACS=emacs-snapshot

before_install:
  - if [ "$EMACS"= "emacs24" ]; then
      sudo apt-get -qq update &&
      sudo apt-get -qq -f install &&
      sudo apt-get -qq install emacs24 emacs24-el curl org-mode;
    fi
    fi
  - if [ "$EMACS" = "emacs-snapshot" ]; then
      sudo add-apt-repository -y ppa:ubuntu-elisp/ppa &&
      sudo apt-get -qq update &&
      sudo apt-get -qq -f install &&
      sudo apt-get -qq install emacs-snapshot emacs-snapshot-el;
    fi

script: make test
